<a href="https://colab.research.google.com/github/clrdjzrn/CPE311/blob/main/Seatwork_6_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
fp = '/content/heart.csv'

In [5]:
import pandas as pd
import numpy as np

In [46]:
data = pd.read_csv(fp)
data

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [23]:
# Identifying all the columns in the dataset
data.columns

Index(['age', 'sex', 'cp', 'trtbps', 'chol', 'fbs', 'restecg', 'thalachh',
       'exng', 'oldpeak', 'slp', 'caa', 'thall', 'output'],
      dtype='object')

In [54]:
# Removing the columns that won't be needed in performing the data analysis
data

     age  sex  cp  chol  fbs  thalachh  oldpeak  slp  caa  thall  output
0     63    1   3   233    1       150      2.3    0    0      1       1
1     37    1   2   250    0       187      3.5    0    0      2       1
2     41    0   1   204    0       172      1.4    2    0      2       1
3     56    1   1   236    0       178      0.8    2    0      2       1
4     57    0   0   354    0       163      0.6    2    0      2       1
..   ...  ...  ..   ...  ...       ...      ...  ...  ...    ...     ...
298   57    0   0   241    0       123      0.2    1    0      3       0
299   45    1   3   264    0       132      1.2    1    0      3       0
300   68    1   0   193    1       141      3.4    1    2      3       0
301   57    1   0   131    0       115      1.2    1    1      3       0
302   57    0   1   236    0       174      0.0    1    1      2       0

[303 rows x 11 columns]

In [49]:
# Identifying the data types
data.dtypes

age           int64
sex           int64
cp            int64
trtbps        int64
chol          int64
fbs           int64
thalachh      int64
exng          int64
oldpeak     float64
slp           int64
caa           int64
thall         int64
output        int64
dtype: object

In [59]:
# Getting all the records
print('The total records in the dataset are:', len(data))

The total records in the dataset are: 303

In [58]:
# Displaying the first 20 records
data.head(20)

    age  sex  cp  chol  fbs  thalachh  oldpeak  slp  caa  thall  output
0    63    1   3   233    1       150      2.3    0    0      1       1
1    37    1   2   250    0       187      3.5    0    0      2       1
2    41    0   1   204    0       172      1.4    2    0      2       1
3    56    1   1   236    0       178      0.8    2    0      2       1
4    57    0   0   354    0       163      0.6    2    0      2       1
5    57    1   0   192    0       148      0.4    1    0      1       1
6    56    0   1   294    0       153      1.3    1    0      2       1
7    44    1   1   263    0       173      0.0    2    0      3       1
8    52    1   2   199    1       162      0.5    2    0      3       1
9    57    1   2   168    0       174      1.6    2    0      2       1
10   54    1   0   239    0       160      1.2    2    0      2       1
11   48    0   2   275    0       139      0.2    2    0      2       1
12   49    1   1   266    0       171      0.6    2    0      2       1
13   64    1   3   211    0       144      1.8    1    0      2       1
14   58    0   3   283    1       162      1.0    2    0      2       1
15   50    0   2   219    0       158      1.6    1    0      2       1
16   58    0   2   340    0       172      0.0    2    0      2       1
17   66    0   3   226    0       114      2.6    0    0      2       1
18   43    1   0   247    0       171      1.5    2    0      2       1
19   69    0   3   239    0       151      1.8    2    2      2       1

In [57]:
# Displaying the last 20 records
data.tail(20)

     age  sex  cp  chol  fbs  thalachh  oldpeak  slp  caa  thall  output
283   40    1   0   223    0       181      0.0    2    0      3       0
284   61    1   0   207    0       138      1.9    2    1      3       0
285   46    1   0   311    0       120      1.8    1    2      3       0
286   59    1   3   204    0       162      0.8    2    2      2       0
287   57    1   1   232    0       164      0.0    2    1      2       0
288   57    1   0   335    0       143      3.0    1    1      3       0
289   55    0   0   205    0       130      2.0    1    1      3       0
290   61    1   0   203    0       161      0.0    2    1      3       0
291   58    1   0   318    0       140      4.4    0    3      1       0
292   58    0   0   225    1       146      2.8    1    2      1       0
293   67    1   2   212    0       150      0.8    1    0      3       0
294   44    1   0   169    0       144      2.8    0    0      1       0
295   63    1   0   187    0       144      4.0    2    2      3       0
296   63    0   0   197    0       136      0.0    1    0      2       0
297   59    1   0   176    1        90      1.0    1    2      1       0
298   57    0   0   241    0       123      0.2    1    0      3       0
299   45    1   3   264    0       132      1.2    1    0      3       0
300   68    1   0   193    1       141      3.4    1    2      3       0
301   57    1   0   131    0       115      1.2    1    1      3       0
302   57    0   1   236    0       174      0.0    1    1      2       0

In [56]:
# Checking if the data has null values
print(data.isnull().sum())

age         0
sex         0
cp          0
chol        0
fbs         0
thalachh    0
oldpeak     0
slp         0
caa         0
thall       0
output      0
dtype: int64

In [61]:
# Add a new colum 'Prediction' that displays "At risk" if output is 1, otherwise Not at Risk
data['Prediction'] = np.where(data['output'] == 1, 'At Risk', 'Not at Risk')
data

,age,sex,cp,chol,fbs,thalachh,oldpeak,slp,caa,thall,output,Prediction
0,63,1,3,233,1,150,2.3,0,0,1,1,At Risk
1,37,1,2,250,0,187,3.5,0,0,2,1,At Risk
2,41,0,1,204,0,172,1.4,2,0,2,1,At Risk
3,56,1,1,236,0,178,0.8,2,0,2,1,At Risk
4,57,0,0,354,0,163,0.6,2,0,2,1,At Risk
...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,241,0,123,0.2,1,0,3,0,Not at Risk
299,45,1,3,264,0,132,1.2,1,0,3,0,Not at Risk
300,68,1,0,193,1,141,3.4,1,2,3,0,Not at Risk
301,57,1,0,131,0,115,1.2,1,1,3,0,Not at Risk
302,57,0,1,236,0,174,0.0,1,1,2,0,Not at Risk

In [63]:
# Dataframes that gathers those who are at Risk to Heart Attack
prdctn = pd.DataFrame(data)
prdctn = data[data['output'] == 1].copy()

prdctn

,age,sex,cp,chol,fbs,thalachh,oldpeak,slp,caa,thall,output,Prediction
0,63,1,3,233,1,150,2.3,0,0,1,1,At Risk
1,37,1,2,250,0,187,3.5,0,0,2,1,At Risk
2,41,0,1,204,0,172,1.4,2,0,2,1,At Risk
3,56,1,1,236,0,178,0.8,2,0,2,1,At Risk
4,57,0,0,354,0,163,0.6,2,0,2,1,At Risk
...,...,...,...,...,...,...,...,...,...,...,...,...
160,56,1,1,240,0,169,0.0,0,0,2,1,At Risk
161,55,0,1,342,0,166,1.2,2,0,2,1,At Risk
162,41,1,1,157,0,182,0.0,2,0,2,1,At Risk
163,38,1,2,175,0,173,0.0,2,4,2,1,At Risk
164,38,1,2,175,0,173,0.0,2,4,2,1,At Risk

In [64]:
# Dataframes that gathers those who are not at risk
prdctn = pd.DataFrame(data)
prdctn = data[data['output'] == 0].copy()

prdctn

,age,sex,cp,chol,fbs,thalachh,oldpeak,slp,caa,thall,output,Prediction
165,67,1,0,286,0,108,1.5,1,3,2,0,Not at Risk
166,67,1,0,229,0,129,2.6,1,2,3,0,Not at Risk
167,62,0,0,268,0,160,3.6,0,2,2,0,Not at Risk
168,63,1,0,254,0,147,1.4,1,1,3,0,Not at Risk
169,53,1,0,203,1,155,3.1,0,0,3,0,Not at Risk
...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,241,0,123,0.2,1,0,3,0,Not at Risk
299,45,1,3,264,0,132,1.2,1,0,3,0,Not at Risk
300,68,1,0,193,1,141,3.4,1,2,3,0,Not at Risk
301,57,1,0,131,0,115,1.2,1,1,3,0,Not at Risk
302,57,0,1,236,0,174,0.0,1,1,2,0,Not at Risk

In [74]:
# Getting the average cholesterol and chest pain
nummean = np.mean(data['chol']),np.mean(data['age'])
nummean

(246.26402640264027, 54.366336633663366)

In [75]:
# Getting the midian of Cholesterol and Age
numed = np.median(data['chol']),np.median(data['age'])
numed

(240.0, 55.0)

In [73]:
# Getting the middle values of Cholesterol and Age
midval = np.median(numed)
midval

147.5

In [69]:
# Getting the standard deviation of maximum heart rate achieved
stdv = np.std(data['thalachh'])
stdv

22.86733258188924

In [76]:
data.describe()

,age,sex,cp,chol,fbs,thalachh,oldpeak,slp,caa,thall,output
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,246.264026,0.148515,149.646865,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,51.830751,0.356198,22.905161,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,126.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,211.000000,0.000000,133.500000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,240.000000,0.000000,153.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,274.500000,0.000000,166.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,564.000000,1.000000,202.000000,6.200000,2.000000,4.000000,3.000000,1.000000

**Analysis**

This dataset shows the heart attack analysis and prediction from ages ranging 29 - 77 years old. I used pandas and numpy to manipulate the dataset and get the prediction of those who are at Risk of getting a heart attack. According to the results of my analysis, ages that ranges 30- 63 years old are prone to heart attack due to high intakes of cholesterol and an average of 0.9669997 chest pains.